# Generated by Django 5.1.6 on 2025-02-08 21:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('menu', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Order ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Customer Phone Number')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Order Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total Price (€)')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('delivery_type', models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery')], default='DINE_IN', max_length=20, verbose_name='Delivery Type')),
                ('table_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Table Number')),
                ('printer_status', models.CharField(choices=[('PENDING', 'Pending'), ('PRINTED', 'Printed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Printer Status')),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Reference')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Discount (€)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Tax Amount (€)')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Is Scheduled?')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Order Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatsession', verbose_name='Chat Session')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Associated Tenant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Unitario (€)')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Precio Final (€)')),
                ('extras', models.JSONField(blank=True, null=True, verbose_name='Extras')),
                ('exclusions', models.JSONField(blank=True, default=list, verbose_name='Exclusiones')),
                ('special_instructions', models.TextField(blank=True, null=True, verbose_name='Instrucciones Especiales')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Descuento (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='IVA (%)')),
                ('preparation_status', models.CharField(choices=[('PENDING', '🟡 Pendiente'), ('IN_PROGRESS', '🔵 En preparación'), ('READY', '🟢 Listo')], default='PENDING', max_length=20, verbose_name='Estado de Preparación')),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Personalizado')),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Servicio')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='Producto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa (Tenant)')),
            ],
        ),
    ]
