# Generated by Django 5.1.6 on 2025-02-08 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAllergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Relación Producto-Alérgeno',
                'verbose_name_plural': 'Relaciones Productos-Alérgenos',
            },
        ),
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Relación Producto-Extra',
                'verbose_name_plural': 'Relaciones Productos-Extras',
            },
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del alérgeno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='allergens/', verbose_name='Ícono del alérgeno')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Alérgeno',
                'verbose_name_plural': 'Alérgenos',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del extra')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('available', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Seleccionado por defecto?')),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad máxima')),
                ('image', models.ImageField(blank=True, null=True, upload_to='extras/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='ExtraAllergen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.allergen', verbose_name='Alérgeno')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.extra', verbose_name='Extra')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Relación Extra-Alérgeno',
                'verbose_name_plural': 'Relaciones Extras-Alérgenos',
            },
        ),
        migrations.AddField(
            model_name='extra',
            name='allergens',
            field=models.ManyToManyField(blank=True, through='menu.ExtraAllergen', to='menu.allergen', verbose_name='Alérgenos'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('available', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('is_special', models.BooleanField(default=False, verbose_name='¿Especial?')),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de preparación (min)')),
                ('spicy_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nivel de picante (0-5)')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock disponible')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías')),
                ('is_vegetarian', models.BooleanField(blank=True, null=True, verbose_name='¿Vegetariano?')),
                ('is_vegan', models.BooleanField(blank=True, null=True, verbose_name='¿Vegano?')),
                ('gluten_free', models.BooleanField(blank=True, null=True, verbose_name='¿Sin gluten?')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
