# Generated by Django 5.1.6 on 2025-02-08 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('printers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_zones',
            field=models.ManyToManyField(blank=True, to='printers.printerzone', verbose_name='Zonas de impresión'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='productallergen',
            name='allergen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.allergen', verbose_name='Alérgeno'),
        ),
        migrations.AddField(
            model_name='productallergen',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productallergen',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, through='menu.ProductAllergen', to='menu.allergen', verbose_name='Alérgenos'),
        ),
        migrations.AddField(
            model_name='productextra',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.extra', verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='productextra',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productextra',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='product',
            name='extras',
            field=models.ManyToManyField(blank=True, through='menu.ProductExtra', to='menu.extra', verbose_name='Extras'),
        ),
        migrations.AlterUniqueTogether(
            name='extraallergen',
            unique_together={('tenant', 'extra', 'allergen')},
        ),
        migrations.AlterUniqueTogether(
            name='productallergen',
            unique_together={('tenant', 'product', 'allergen')},
        ),
        migrations.AlterUniqueTogether(
            name='productextra',
            unique_together={('tenant', 'product', 'extra')},
        ),
    ]
