# Generated by Django 5.1.6 on 2025-02-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='print_zones',
            field=models.ManyToManyField(blank=True, to='printers.printerzone', verbose_name='Zonas de impresión'),
        ),
    ]
