# Generated by Django 5.1.6 on 2025-02-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_print_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=100, verbose_name='Orden de aparición'),
        ),
    ]
