# Generated by Django 5.1.6 on 2025-02-08 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100, verbose_name='ID del Evento')),
                ('event_type', models.CharField(max_length=50, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Datos del Webhook')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Evento del Webhook de WhatsApp',
                'verbose_name_plural': 'Eventos del Webhook de WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Teléfono')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('profile_picture_url', models.URLField(blank=True, null=True, verbose_name='Foto de Perfil')),
                ('wa_id', models.CharField(max_length=50, unique=True, verbose_name='ID de WhatsApp')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Última Interacción')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Contacto de WhatsApp',
                'verbose_name_plural': 'Contactos de WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Mensaje')),
                ('from_number', models.CharField(max_length=20, verbose_name='Número Remitente')),
                ('to_number', models.CharField(max_length=20, verbose_name='Número Destinatario')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('sticker', 'Sticker'), ('location', 'Ubicación')], max_length=50, verbose_name='Tipo de Mensaje')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='sent', max_length=50, verbose_name='Estado')),
                ('direction', models.CharField(choices=[('inbound', 'Entrante'), ('outbound', 'Saliente')], max_length=10, verbose_name='Dirección')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Mensaje de WhatsApp',
                'verbose_name_plural': 'Mensajes de WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], max_length=50, verbose_name='Estado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='whatsapp.whatsappmessage', verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Estado de Mensaje',
                'verbose_name_plural': 'Estados de Mensajes',
            },
        ),
    ]
