# Generated by Django 5.1.6 on 2025-02-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_policy_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
