# Generated by Django 5.1.6 on 2025-02-12 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappcontact_last_policy_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappcontact',
            options={'verbose_name': 'WhatsApp Contact', 'verbose_name_plural': 'WhatsApp Contacts'},
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Interaction'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='last_policy_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Policy Sent'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Picture URL'),
        ),
        migrations.AlterField(
            model_name='whatsappcontact',
            name='wa_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='WhatsApp ID'),
        ),
    ]
