# Generated by Django 5.1.6 on 2025-02-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_whatsappcontact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='first_buy',
            field=models.BooleanField(default=True, verbose_name='First Buy'),
        ),
    ]
