# Generated by Django 5.1.6 on 2025-02-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappcontact_first_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='policy_accepted',
            field=models.BooleanField(default=False, verbose_name='Policy Accepted'),
        ),
    ]
