# Generated by Django 5.1.6 on 2025-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappcontact_policy_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_message_before_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Last Message Before Policy'),
        ),
    ]
