# Generated by Django 5.1.6 on 2025-02-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_whatsappcontact_last_message_before_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='last_policy_sent',
        ),
    ]
