# Generated by Django 5.1.6 on 2025-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_remove_whatsappcontact_last_policy_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='accepts_promotions',
            field=models.BooleanField(null=True, verbose_name='Acepta Promociones'),
        ),
    ]
