# Generated by Django 5.1.6 on 2025-02-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_whatsappcontact_accepts_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_detected_language',
            field=models.CharField(default='es', max_length=5),
        ),
    ]
