# Generated by Django 5.1.6 on 2025-02-12 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_category_print_zones'),
        ('whatsapp', '0002_whatsappcontact_last_policy_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo'), ('free_product', 'Producto gratis')], max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_products', models.ManyToManyField(blank=True, to='menu.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_used', to='whatsapp.whatsappcontact')),
            ],
        ),
    ]
