# Generated by Django 5.1.6 on 2025-02-08 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Session ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Session')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Session Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Session End Time')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='Conversation Context')),
                ('last_detected_language', models.CharField(default='es', max_length=5)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession', verbose_name='Chat Session')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20, verbose_name='Sender Role')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantsession', verbose_name='Assistant Session')),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=100, unique=True, verbose_name='Request ID')),
                ('endpoint', models.CharField(max_length=100, verbose_name='API Endpoint')),
                ('payload', models.JSONField(verbose_name='Request Payload')),
                ('response', models.JSONField(verbose_name='API Response')),
                ('status_code', models.IntegerField(verbose_name='HTTP Status Code')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
        ),
    ]
