# Generated by Django 5.1.6 on 2025-02-13 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_has_first_buy_promo'),
        ('whatsapp', '0008_whatsappcontact_accepts_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('permissions', models.CharField(choices=[('no_payment', 'Sin pago'), ('priority', 'Prioridad'), ('discount', 'Descuento especial')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsappcontact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'unique_together': {('contact', 'tenant')},
            },
        ),
    ]
