# Generated by Django 5.1.6 on 2025-02-08 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Printer Zone Name')),
                ('printer_ip', models.GenericIPAddressField(verbose_name='Printer IP Address')),
                ('printer_port', models.PositiveIntegerField(default=9100, verbose_name='Printer Port')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Printer Zone',
                'verbose_name_plural': 'Printer Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Ticket Content')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PRINTED', 'Printed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Print Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_tickets', to='orders.order', verbose_name='Order')),
                ('printer_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='printers.printerzone', verbose_name='Printer Zone')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Print Ticket',
                'verbose_name_plural': 'Print Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
