# Generated by Django 5.1.6 on 2025-02-08 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Phone number of the client.', max_length=20, verbose_name='Client Phone Number')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the session is active.', verbose_name='Active Session')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='When the session started.', verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the session ended.', null=True, verbose_name='End Time')),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Timestamp of last interaction.', null=True, verbose_name='Last Interaction')),
                ('context_data', models.JSONField(blank=True, help_text='Stores conversation context for AI processing.', null=True, verbose_name='Context Data')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('client', 'Client'), ('bot', 'Bot'), ('system', 'System')], help_text='Indicates who sent the message.', max_length=50, verbose_name='Sender')),
                ('message_content', models.TextField(help_text='Text content of the message.', verbose_name='Message Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the message was sent.', verbose_name='Timestamp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Chat Session')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_conversation', models.JSONField(help_text='Stores the full chat history in JSON format.', verbose_name='Full Conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the conversation history was stored.', verbose_name='Created At')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='chat.chatsession', verbose_name='Chat Session')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Conversation History',
                'verbose_name_plural': 'Conversation Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
